language: generic
sudo: required

services:
  - docker
env:
  global:
    SHA=$(git rev-parse HEAD)
    
before_script:
   - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
   - curl -sS -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/kubectl
   - chmod +x ./kubectl ./aws-iam-authenticator
   - export PATH=$PWD/:$PATH
   - sudo apt-get update
   - sudo apt-get -y install python3-pip
   - sudo apt-get -y install awscli
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t jzhao5/react-test -f ./client/Dockerfile.dev ./client
  - docker run -e CI=true jzhao5/react-test npm run test

after_script:
  - docker build -t jzhao5/multi-client:latest jzhao5/multi-client2:$SHA -f ./client/Dockerfile ./client
  - docker build -t jzhao5/multi-api:latest jzhao5/multi-server2:$SHA -f ./server/Dockerfile ./server
  - docker build -t jzhao5/multi-worker:latest jzhao5/multi-worker2:$SHA -f ./worker/Dockerfile ./worker
  - docker push jzhao5/multi-client2:latest
  - docker push jzhao5/multi-server2:latest
  - docker push jzhao5/multi-worker2:latest
  - docker push jzhao5/multi-client2:$SHA
  - docker push jzhao5/multi-server2:$SHA
  - docker push jzhao5/multi-worker2:$SHA
  - export $AWS_ACCESS_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId')"
  - export $AWS_SECRET_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey')"
  - aws eks update-kubeconfig --name sandbox
  - kubectl apply -f k8s --namespace=multi-k8s

#deploy:
  #provider: script
  #script: bash ./deploy.sh
  #on:
    #branch: master
  #access_key_id: $AWS_ACCESS_KEY
  #secret_access_key: $AWS_SECRET_KEY